(source gnu "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
(source melpa "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")

(depends-on "which-key")
(depends-on "evil")
(depends-on "diminish")
(depends-on "general")

(package-file "lisp/+shell.el")
(package-file "lisp/+buffer.el")
(package-file "lisp/+window.el")
(package-file "lisp/+projectile.el")
(package-file "lisp/+editor.el")
(package-file "lisp/+company.el")
(package-file "lisp/+flycheck.el")
(package-file "lisp/+lsp.el")
(package-file "lisp/+go.el")
